import { Controller, Post, Body, HttpCode, HttpStatus } from '@nestjs/common';
import { AuthService } from './auth.service';
import { RegisterDto, LoginDto } from './dto/auth.dto';
import { ApiTags, ApiOperation, ApiResponse } from '@nestjs/swagger';

@ApiTags('Auth') // Groups these endpoints under "Auth" in Swagger UI
@Controller('auth') // Defines the base route as /auth
export class AuthController {
  // Inject the AuthService which contains all our core logic
  constructor(private readonly authService: AuthService) {}

  /**
   * Endpoint: POST /auth/register
   * Process: Takes the validated user details from the RegisterDto and hands it to the service.
   */
  @Post('register')
  @ApiOperation({ summary: 'Register a new user' })
  @ApiResponse({ status: 201, description: 'User successfully registered.' })
  @ApiResponse({ status: 409, description: 'Email already exists.' })
  async register(@Body() dto: RegisterDto) {
    return this.authService.register(dto);
  }

  /**
   * Endpoint: POST /auth/login
   * Process: Takes the LoginDto, ensures it executes with a 200 OK (default POST is 201),
   * and returns the JWT generated by the auth service.
   */
  @Post('login')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Login user' })
  @ApiResponse({ status: 200, description: 'User successfully logged in.' })
  @ApiResponse({ status: 401, description: 'Invalid credentials.' })
  async login(@Body() dto: LoginDto) {
    return this.authService.login(dto);
  }
}
